Bytecode generation
JetBrains-Research/reflekt pull request #21
Opened 2020-11-09 07:34 UTC by isomethane

2020-11-09 14:59 UTC, nbirillo requested changes
Great!

2020-11-09 14:59 UTC, nbirillo commented on reflekt-plugin/src/main/kotlin/io/reflekt/plugin/generation/bytecode/Util.kt
> +        anew(Type.getObjectType("kotlin/TypeCastException"))
You use different consts like `kotlin/TypeCastException` for paths. I think we can create storage for them or something like this. I mean, if you use string constant you can make a mistake. But if we use variables, we are sure the same variable has the same value in the different places

2020-11-09 14:59 UTC, nbirillo commented on reflekt-plugin/src/main/kotlin/io/reflekt/plugin/generation/bytecode/ReflektGeneratorExtension.kt
> +                items.getValue(invokeArguments).map {
getValue throws errors if the key does not exist. Is it ok? Let's use 
```
items[invokeArguments]?.map {
                    ...
                } ?: emptyList()
```
or
```
items[invokeArguments]?.map {
                    ...
                } ?: error("Some error message")
```

2020-11-09 14:59 UTC, nbirillo commented on reflekt-plugin/src/main/kotlin/io/reflekt/plugin/generation/bytecode/ReflektGeneratorExtension.kt
> +package io.reflekt.plugin.generation.bytecode
I think we should add some comments to this file, especially in `ReflektInvokeNames` class.

2020-11-09 14:59 UTC, nbirillo commented on reflekt-plugin/src/main/kotlin/io/reflekt/plugin/generation/bytecode/ReflektGeneratorExtension.kt
> +    override fun applyFunction(receiver: StackValue, resolvedCall: ResolvedCall<*>, c: ExpressionCodegenExtension.Context): StackValue? {
Please, use `messageCollector` to log some intermediate information to make debugging easier, for example before `return null` and etc

2020-12-03 16:56 UTC, nbirillo reviewed
Thanks a lot, it looks great! I have one question: can we add several tests for the bytecode generation to be sure that the generated code is correct? We can do it in another PR of course. What do you think?

2020-12-03 20:47 UTC, isomethane commented
Yes, I will add tests.

2020-12-04 13:04 UTC, nbirillo approved these changes
Cool! Let's add tests in the next PR

2020-12-04 13:05 UTC, merged